### ISSUE TITLE
代码里面存在两处验证码有效期定义

### ISSUE THREAD

**Issue by ihipop** [Tinywan/webman-captcha#2]
https://github.com/Tinywan/webman-captcha/blob/46dca7946c5bcdd1ae4f7f67e1c9bee2997cb066/src/config/plugin/tinywan/captcha/app.php#L36 

对应

https://github.com/Tinywan/webman-captcha/blob/46dca7946c5bcdd1ae4f7f67e1c9bee2997cb066/src/Captcha.php#L151  

但是

https://github.com/Tinywan/webman-captcha/blob/46dca7946c5bcdd1ae4f7f67e1c9bee2997cb066/src/config/plugin/tinywan/captcha/app.php#L28

似乎没有任何地方用到？

**Comment by Tinywan** [comment]
欢迎提交PR
